### PR TITLE
Initial Alibaba oss backend setup

### LINKED ISSUE #65: Add Alibaba OSS Storage Backend
**Is your feature request related to a problem? Please describe.**

As a user of the [Alibaba Cloud](https://www.alibabacloud.com), I want to use [Alibaba OSS Storage](https://www.alibabacloud.com/product/oss) to persist my cache, so that I can reuse the storage system that I already know.

**Describe the solution you'd like**
Alibaba OSS Storage Backend

**Describe alternatives you've considered**
using a separate storage backend that already exists in drone-cache

**Additional context**
none

### PR DESCRIPTION
**Pull request by rugwirobaker**
Fixes #65

## Proposed Changes
- add `github.com/aliyun/aliyun-oss-go-sdk/oss` dependency.
- Implement Alibaba Object Storage Service backend.
- Add Alibaba OSS to plugins config

### Checklist

- [x] Read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] Read the [**CODE OF CONDUCT**](CODE_OF_CONDUCT.md) document.
- [x] Add tests to cover changes.
- [x] Ensure your code follows the code style of this project.
- [ ] Ensure CI and all other PR checks are green OR
    - [x ] Code compiles correctly.
    - [ ] Created tests which fail without the change (if possible).
    - [ ] All new and existing tests passed.
- [ ] Add your changes to `Unreleased` section of [CHANGELOG](CHANGELOG.md).
- [ ] Improve and update the [README](README.md) (if necessary).
- [ ] Ensure [documentation](./DOCS.md) is up-to-date. The same file will be updated in [plugin index](https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md) when your PR is accepted, so it will be available for end-users at http://plugins.drone.io.

### CODE REVIEW

**Comment by kakkoyun** [comment]
Hey @rugwirobaker, I will try to give this one a push this weekend or in the next week.

What's left? Do you need help with something specific?

**Comment by kakkoyun** [comment]
Hey @rugwirobaker, any update on this?

**Comment by rugwirobaker** [comment]
@kakkoyun sorry I have been busy with other commitments. Just came back to it. Would actually appreciate help regarding testing since there all on integration tests in the backend package I assume you have to create an account with the corresponding backend service and live test? And of course documentation.

**Comment by kakkoyun** [comment]
@rugwirobaker Happy to help. I've been working on a major refactoring after a couple of backends merged, in the same PR I'll be introducing an easy way to test backends. #86 

I'll ping you when it's merged if you still want to continue working on it.

**Comment by rugwirobaker** [comment]
I'm actually working on it right now. Just have to comply with the linter and we are go.

**Comment by rugwirobaker** [comment]
@kakkoyun do you have any ideas on whether are alibaba-oss emulators that we can easly install into the dev/test environment? I'm thinking something like azurite.

**Comment by kakkoyun** [comment]
@rugwirobaker I found this https://github.com/aliyun/oss-emulator from their official documentation https://www.alibabacloud.com/help/doc-detail/44075.html Unfortunately documentation in Chinese, however, code itself is readable. Also, there are some docker images https://hub.docker.com/search?q=oss-emulator&type=image It should work if we can figure how to run it.

What do you think?

**Comment by kakkoyun** [comment]
@rugwirobaker We have changed overall structure, you may want to have a look at the latest state of master. It'd make more sense to check out a new branch and apply your changes rather than reading it.

**Comment by kakkoyun** [comment]
@rugwirobaker Any plans to push this to the finish line?

**Comment by rugwirobaker** [comment]
@kakkoyun I'm working on it this weekend. Should have something by Sunday.

**Comment by kakkoyun** [comment]
@rugwirobaker Amazing news! Go for it

**Comment by kakkoyun** [comment]
Hey @rugwirobaker, do you still think we can do this?

**Comment by bdebyl** [comment]
@rugwirobaker is this still a desired addition to drone cache, or anyone else want to take ownership? Otherwise I will most likely close the pull request due within the coming weeks.

**Comment by bdebyl** [comment]
Solved by https://github.com/meltwater/drone-cache/pull/223

**Pull request closed without merging**
