### PR TITLE
Fix NoCredentialProviders error when accessing public bucket on Minio

### LINKED ISSUE #132: NoCredentialProviders error when accessing public bucket on Minio
**Describe the bug**
`NoCredentialProviders` error occurs when accessing Minio public bucket without setting credentials

**To Reproduce**
Set Minio bucket policy to download.
Try to access the files in the bucket without credential

**Expected behavior**
To be able to access public cached files

**Additional context**
The problem lies in the `s3.go` file. If the credentials are not set then `conf.Credentials` must be set to `credentials.AnonymousCredentials`

### PR DESCRIPTION
**Pull request by Codebreaker101**
Fixes [#132](https://github.com/meltwater/drone-cache/issues/132)

### Checklist

- [x] Read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] Read the [**CODE OF CONDUCT**](CODE_OF_CONDUCT.md) document.
- [x] Add tests to cover changes.
- [x] Ensure your code follows the code style of this project.
- [x] Ensure CI and all other PR checks are green OR
    - [x] Code compiles correctly.
    - [x] Created tests which fail without the change (if possible).
    - [x] All new and existing tests passed.
- [x] Add your changes to `Unreleased` section of [CHANGELOG](CHANGELOG.md).
- [x] Improve and update the [README](README.md) (if necessary).
- [x] Ensure [documentation](./DOCS.md) is up-to-date. The same file will be updated in [plugin index](https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md) when your PR is accepted, so it will be available for end-users at http://plugins.drone.io.

### CODE REVIEW

**Comment by Codebreaker101** [comment]
@kakkoyun any updates on this?

**Comment by kakkoyun** [comment]
@Codebreaker101 And rebasing your branch onto latest master should solve the CI problems.

**Comment by Codebreaker101** [comment]
I have not tested it on AWS S3, but the object was taken straight from the [documentation](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#pkg-variables) so it _should_ work with no issues.

**Comment by jimsheldon** [comment]
Looks like this introduced a regression that is being tracked in #188

**Pull request merged**
