### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by kakkoyun**
## Proposed Changes

- Add code of conduct

### Checklist

- [x] Read the **CONTRIBUTING** document.
- [ ] Add tests to cover my changes.
- [x] Make sure your code follows the code style of this project
- [ ] Make sure CI and all other PR checks are green OR
    - [ ] Code compiles correctly/
    - [ ] Created tests which fail without the change (if possible)/
    - [ ] All new and existing tests passed.
- [ ] Extended and update the README (if necessary).
- [ ] Make sure [documentation](./DOCS.md) is up-to-date. Same file should also be updated in [plugin index](https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md) by sending a PR to that repository.

### CODE REVIEW

**Comment by spier** [comment]
Hey @kakkoyun. 

Great idea with a code of conduct.

Two questions:

1. The file https://github.com/meltwater/drone-cache/blob/master/CONTRIBUTING.md also contains a code of conduct which looks similar to the one that gets added here. Do you want to keep both?
1. Do you want to link to the new code of conduct from the README?

**Comment by kakkoyun** [comment]
Hey @spier, thanks a lot for pointing these issues. 
1. I'll remove old one and add a link to this one. I just want to make it more explicit.
2. I'll update the README.

**Comment by spier** [comment]
@kakkoyun I have some time, so if you want me to, I can also do these fixes. Just let me know so that we don't do duplicate work.

**Comment by kakkoyun** [comment]
Go ahead. That would be great actually. Thanks a lot.

**Pull request merged**
