### PR TITLE
Add compression level CLI option

### LINKED ISSUE #72: Feature request: log gzip compression ratio
**Is your feature request related to a problem? Please describe.**
Currently I'm investigating a slowdown in the caching steps for a build. I'm aware the data being cached has grown significantly, so I wondered how "just tar" vs tar with gzip would perform.

Turns out, tar without gzip performed worse because I was getting a whopping 80% size reduction.

**Describe the solution you'd like**
In the archiving (and extraction?) steps, I would like to see an additional line that prints out the gzip compression ratio achieved.

**Describe alternatives you've considered**
Duplicate the caching steps, modify the copy to use tar at a different cache key, compare filesizes at the backend (in my case minio's GUI).

**Additional context**
Example build with and without gzip.
https://drone.teamopen.dev/teamopen-dev/sourcecred-stack-lookup/79

Results in the layers:
```
# With gzip
.scores 72.84 MB
.sourcecred 768.31 MB

# Without gzip
.scores 535.22 MB
.sourcecred 3.61 GB
```

### PR DESCRIPTION
**Pull request by kakkoyun**
This PR adds compression level CLI option.
Also piggybacks a lot of refactorings. (sorry for lengthy PR)

Fixes #72 

## Proposed Changes

- Add compression level CLI option
- Logs compression level when debug enabled
- Upgrade go 1.13
- Refactor error messages by using new go errors
- Introduce structured logging
- Refactor Makefile
- Upgrade linter, Golangci-lint
- Automate usage doc creation
- Update docs

### Description

Users now can specify compression level.

### Checklist

- [x] Read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] Read the [**CODE OF CONDUCT**](CODE_OF_CONDUCT.md) document.
- [x] Add tests to cover changes.
- [x] Ensure your code follows the code style of this project.
- [x] Ensure CI and all other PR checks are green OR
    - [x] Code compiles correctly.
    - [x] Created tests which fail without the change (if possible).
    - [x] All new and existing tests passed.
- [x] Add your changes to `Unreleased` section of [CHANGELOG](CHANGELOG.md).
- [x] Improve and update the [README](README.md) (if necessary).
- [ ] Ensure [documentation](./DOCS.md) is up-to-date. The same file will be updated in [plugin index](https://github.com/drone/drone-plugin-index/blob/master/content/meltwater/drone-cache/index.md) when your PR is accepted, so it will be available for end-users at http://plugins.drone.io.

### CODE REVIEW

**Comment by kakkoyun** [comment]
@limayekaiwalya It's a long but a good one. Please take your time.

**Comment by limayekaiwalya** [comment]
@kakkoyun , Looking at it. Sorry for the long response times. I am taking a bit longer to understand the existing code so I can provide better reviews  :)

**Comment by kakkoyun** [comment]
@limayekaiwalya Please tell me if you need anything to understand the existing codebase, happy to help.

**Comment by limayekaiwalya** [comment]
@kakkoyun A questions out of curiosity: Why did we switch to `fmt.Errorf` from `errors.Wrap` ?

**Comment by kakkoyun** [comment]
@limayekaiwalya The real change is about `%w` in `fmt.Errorf` which has introduced recently with 1.13 release of Go, now we can wrap standard errors with a context without a need of an external package. Further, since we don't actually utilize all the features from `pkg/errors` package, like stack capture etc., I thought we don't need any other library for that, hence I removed it.

**Pull request merged**
