### PR TITLE
Parallelize gzip with `github.com/klauspost/pgzip`

### LINKED ISSUE #94: Add more archive formats
https://github.com/mholt/archiver

### PR DESCRIPTION
**Pull request by isac322**
Please read [CONTRIBUTING.md](CONTRIBUTING.md) for details on our [code of conduct](CODE_OF_CONDUCT.md), and the process for submitting pull requests to us.

Fixes #94 

## Proposed Changes

- Parallelize gzip with https://github.com/klauspost/pgzip

### Description

`github.com/klauspost/pgzip` is drop in replacement of `compress/gzip` and it achieve better performance via parallelizing compression.

### Checklist

- [x] Read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] Read the [**CODE OF CONDUCT**](CODE_OF_CONDUCT.md) document.
- [x] Ensure your code follows the code style of this project.
- [x] Ensure CI and all other PR checks are green OR
    - [x] Code compiles correctly.
    - [x] All new and existing tests passed.
- [x] Add your changes to `Unreleased` section of [CHANGELOG](CHANGELOG.md).

### CODE REVIEW

**Comment by jimsheldon** [comment]
Thanks for the contribution! It looks like this branch needs to be rebased off master, can you please update your branch? Thanks

**Comment by isac322** [comment]
@jimsheldon done!

**Review by kakkoyun — APPROVED** [review]
LGTM 💯

**Comment by kakkoyun** [comment]
Leaving the decision to merge to @jimsheldon

**Review by kakkoyun — APPROVED** [review]

**Comment by kakkoyun** [comment]
@isac322 Why did you close it? I think this could be used.

**Pull request closed without merging**
